const apiDetails = {
  // baseUrl: "http://56.228.24.109:8080/api",
  // baseUrl: "https://mentorbooster.duckdns.org/api",
  baseUrl: "https://clinical-psychology-node-backend.onrender.com/api",
  endPoint: {
    getAllSlotsForTherapist: "/getTimeSlotsForTherapist",
    checkout: "/checkout",
    therapist_profile: "/therapist/getProfileDetails",
    therapist_update: "/therapist/updateProfile",
    client_profile: "/client/getProfileDetails",
    client_update: "/client/updateProfile",
    filter: "therapist/search",
    login: "/auth/login",
    signUp: "/client/register",
    sendOtp: "/auth/sendOtp",
    verifyOtp: "/auth/verifyOtp",
    changePassword: "/auth/changePassword",
    sseToken: "/ai-therapist/sse-token",
    resume_upload: "/s3/upload/therapist-resumes",
    therapist_register: "/therapist/register",
    image_upload: "/s3/upload/therapist-images",
    client_image: "/s3/upload/client-images",
    getAllNotApprovedTherapist: "/admin/getDashboardDetails",
    therapistStatusUpdate: "/admin/therapists",
    getAllAdminTherapists: "/admin/getAllTherapistSessions",
    getAllAdminClients: "/admin/getAllClientSessions",
    getClientSessions: "/client/getAppointments",
    getTherapistSessions: "/therapist/getAppointments",
    getAllTherapistsOverview: "/admin/therapists/overview",
    getAllClientsOverview: "/admin/clients/overview",
    clientSessionCancel: "/client/bookings",
    getScheduleBooking: "/client/bookings",
    Contact: "/contact-messages",
  },
};

export default apiDetails;
